twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic   : input_joy/cmd_vel
        timeout : 0.5
        priority: 99
      keyboard: 
        topic   : input_key/cmd_vel
        timeout : 0.5
        priority: 90